# fly.toml app configuration file generated for aigatha on 2023-12-06T18:48:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aigatha"
primary_region = "iad"
console_command = "/rails/bin/rails console"

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    timeout = "2s"

[deploy]
  release_command = "./bin/rails db:prepare"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
